-- MySQL Script generated by MySQL Workbench
-- Fri Nov 15 08:14:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema invef_bd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `invef_bd` ;

-- -----------------------------------------------------
-- Schema invef_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `invef_bd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `invef_bd` ;

-- -----------------------------------------------------
-- Table `almacen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almacen` ;

CREATE TABLE IF NOT EXISTS `almacen` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `stand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stand` ;

CREATE TABLE IF NOT EXISTS `stand` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `detalle` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `Almacen_id` INT(11) NOT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Stand_Almacen1`
    FOREIGN KEY (`Almacen_id`)
    REFERENCES `almacen` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Stand_Almacen1_idx` ON `stand` (`Almacen_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `casillero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `casillero` ;

CREATE TABLE IF NOT EXISTS `casillero` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `detalle` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `Stand_id` INT(11) NOT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_casillero_Stand1`
    FOREIGN KEY (`Stand_id`)
    REFERENCES `stand` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_casillero_Stand1_idx` ON `casillero` (`Stand_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ocupacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocupacion` ;

CREATE TABLE IF NOT EXISTS `ocupacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(450) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `recomendacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recomendacion` ;

CREATE TABLE IF NOT EXISTS `recomendacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(450) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

CREATE TABLE IF NOT EXISTS `cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(150) NOT NULL,
  `apellidos` VARCHAR(150) NOT NULL,
  `dni` CHAR(11) NOT NULL,
  `correo` VARCHAR(250) NULL DEFAULT NULL,
  `direccion` VARCHAR(450) NULL DEFAULT NULL,
  `fecnacimiento` DATE NULL DEFAULT NULL,
  `edad` VARCHAR(45) NULL DEFAULT NULL,
  `genero` VARCHAR(45) NULL DEFAULT NULL,
  `foto` VARCHAR(450) NULL DEFAULT NULL,
  `facebook` VARCHAR(450) NULL DEFAULT NULL,
  `ingmax` VARCHAR(450) NULL DEFAULT NULL,
  `ingmin` VARCHAR(450) NULL DEFAULT NULL,
  `gasmax` VARCHAR(450) NULL DEFAULT NULL,
  `gasmin` VARCHAR(450) NULL DEFAULT NULL,
  `estado` TINYINT(4) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `ocupacion_id` INT(11) NOT NULL,
  `recomendacion_id` INT(11) NOT NULL,
  `evaluacion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `whatsapp` VARCHAR(45) NULL DEFAULT NULL,
  `telfreferencia` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cliente_ocupacion1`
    FOREIGN KEY (`ocupacion_id`)
    REFERENCES `ocupacion` (`id`),
  CONSTRAINT `fk_cliente_recomendacion1`
    FOREIGN KEY (`recomendacion_id`)
    REFERENCES `recomendacion` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_cliente_ocupacion1_idx` ON `cliente` (`ocupacion_id` ASC) VISIBLE;

CREATE INDEX `fk_cliente_recomendacion1_idx` ON `cliente` (`recomendacion_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `telefono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefono` ;

CREATE TABLE IF NOT EXISTS `telefono` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliente_telefono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente_telefono` ;

CREATE TABLE IF NOT EXISTS `cliente_telefono` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `telefono_id` INT(11) NOT NULL,
  `cliente_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cliente_telefono_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`),
  CONSTRAINT `fk_cliente_telefono_telefono1`
    FOREIGN KEY (`telefono_id`)
    REFERENCES `telefono` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_cliente_telefono_telefono1_idx` ON `cliente_telefono` (`telefono_id` ASC) VISIBLE;

CREATE INDEX `fk_cliente_telefono_cliente1_idx` ON `cliente_telefono` (`cliente_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tipousuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipousuario` ;

CREATE TABLE IF NOT EXISTS `tipousuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `email` VARCHAR(450) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cliente_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente_user` ;

CREATE TABLE IF NOT EXISTS `cliente_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` TINYINT(4) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `cliente_id` INT(11) NOT NULL,
  `users_id` INT(11) NOT NULL,
  `tipousuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cliente_user_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`),
  CONSTRAINT `fk_cliente_user_tipousuario1`
    FOREIGN KEY (`tipousuario_id`)
    REFERENCES `tipousuario` (`id`),
  CONSTRAINT `fk_cliente_user_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_cliente_user_cliente1_idx` ON `cliente_user` (`cliente_id` ASC) VISIBLE;

CREATE INDEX `fk_cliente_user_users1_idx` ON `cliente_user` (`users_id` ASC) VISIBLE;

CREATE INDEX `fk_cliente_user_tipousuario1_idx` ON `cliente_user` (`tipousuario_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleado` ;

CREATE TABLE IF NOT EXISTS `empleado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `apellido` VARCHAR(250) NOT NULL,
  `dni` CHAR(11) NOT NULL,
  `direccion` VARCHAR(450) NULL DEFAULT NULL,
  `fecnacimiento` DATE NULL DEFAULT NULL,
  `edad` VARCHAR(45) NULL DEFAULT NULL,
  `genero` VARCHAR(45) NULL DEFAULT NULL,
  `foto` VARCHAR(450) NULL DEFAULT NULL,
  `estado` TINYINT(4) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `ocupacion_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_empleado_ocupacion1`
    FOREIGN KEY (`ocupacion_id`)
    REFERENCES `ocupacion` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_empleado_ocupacion1_idx` ON `empleado` (`ocupacion_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tipogarantia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipogarantia` ;

CREATE TABLE IF NOT EXISTS `tipogarantia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `precMax` VARCHAR(45) NULL DEFAULT NULL,
  `precMin` VARCHAR(45) NULL DEFAULT NULL,
  `detalle` VARCHAR(450) NULL DEFAULT NULL,
  `pureza` VARCHAR(450) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `garantia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `garantia` ;

CREATE TABLE IF NOT EXISTS `garantia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `detalle` VARCHAR(450) NULL DEFAULT NULL,
  `estado` TINYINT(4) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `tipogarantia_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_garantia_tipogarantia1`
    FOREIGN KEY (`tipogarantia_id`)
    REFERENCES `tipogarantia` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_garantia_tipogarantia1_idx` ON `garantia` (`tipogarantia_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tipoprestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipoprestamo` ;

CREATE TABLE IF NOT EXISTS `tipoprestamo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `detalle` VARCHAR(450) NULL DEFAULT NULL,
  `imagen` VARCHAR(450) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cotizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cotizacion` ;

CREATE TABLE IF NOT EXISTS `cotizacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente_id` INT(11) NOT NULL,
  `empleado_id` INT(11) NOT NULL,
  `garantia_id` INT(11) NOT NULL,
  `max` VARCHAR(45) NOT NULL,
  `min` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `estado` TINYINT(4) NOT NULL,
  `tipoprestamo_id` INT(11) NOT NULL,
  `precio` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cotizacion_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`),
  CONSTRAINT `fk_cotizacion_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `empleado` (`id`),
  CONSTRAINT `fk_cotizacion_garantia1`
    FOREIGN KEY (`garantia_id`)
    REFERENCES `garantia` (`id`),
  CONSTRAINT `fk_cotizacion_tipoprestamo1`
    FOREIGN KEY (`tipoprestamo_id`)
    REFERENCES `tipoprestamo` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_cotizacion_cliente1_idx` ON `cotizacion` (`cliente_id` ASC) VISIBLE;

CREATE INDEX `fk_cotizacion_empleado1_idx` ON `cotizacion` (`empleado_id` ASC) VISIBLE;

CREATE INDEX `fk_cotizacion_garantia1_idx` ON `cotizacion` (`garantia_id` ASC) VISIBLE;

CREATE INDEX `fk_cotizacion_tipoprestamo1_idx` ON `cotizacion` (`tipoprestamo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `empleado_telefono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleado_telefono` ;

CREATE TABLE IF NOT EXISTS `empleado_telefono` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` TINYINT(4) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `telefono_id` INT(11) NOT NULL,
  `empleado_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_empleado_telefono_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `empleado` (`id`),
  CONSTRAINT `fk_empleado_telefono_telefono1`
    FOREIGN KEY (`telefono_id`)
    REFERENCES `telefono` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_empleado_telefono_telefono1_idx` ON `empleado_telefono` (`telefono_id` ASC) VISIBLE;

CREATE INDEX `fk_empleado_telefono_empleado1_idx` ON `empleado_telefono` (`empleado_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `empleado_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleado_user` ;

CREATE TABLE IF NOT EXISTS `empleado_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` TINYINT(4) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL,
  `empleado_id` INT(11) NOT NULL,
  `tipousuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_empleado_user_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `empleado` (`id`),
  CONSTRAINT `fk_empleado_user_tipousuario1`
    FOREIGN KEY (`tipousuario_id`)
    REFERENCES `tipousuario` (`id`),
  CONSTRAINT `fk_empleado_user_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_empleado_user_users1_idx` ON `empleado_user` (`users_id` ASC) VISIBLE;

CREATE INDEX `fk_empleado_user_empleado1_idx` ON `empleado_user` (`empleado_id` ASC) VISIBLE;

CREATE INDEX `fk_empleado_user_tipousuario1_idx` ON `empleado_user` (`tipousuario_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `interes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `interes` ;

CREATE TABLE IF NOT EXISTS `interes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `porcentaje` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mora` ;

CREATE TABLE IF NOT EXISTS `mora` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prestamo` ;

CREATE TABLE IF NOT EXISTS `prestamo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `monto` VARCHAR(45) NOT NULL,
  `fecinicio` DATE NOT NULL,
  `fecfin` DATE NOT NULL,
  `total` VARCHAR(45) NOT NULL,
  `estado` TINYINT(4) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `cotizacion_id` INT(11) NOT NULL,
  `casillero_id` INT(11) NOT NULL,
  `interes_id` INT(11) NOT NULL,
  `mora_id` INT(11) NOT NULL,
  `macro` VARCHAR(45) NULL DEFAULT NULL,
  `intpagar` VARCHAR(45) NULL DEFAULT NULL,
  `morapagar` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_prestamo_casillero1`
    FOREIGN KEY (`casillero_id`)
    REFERENCES `casillero` (`id`),
  CONSTRAINT `fk_prestamo_cotizacion1`
    FOREIGN KEY (`cotizacion_id`)
    REFERENCES `cotizacion` (`id`),
  CONSTRAINT `fk_prestamo_interes1`
    FOREIGN KEY (`interes_id`)
    REFERENCES `interes` (`id`),
  CONSTRAINT `fk_prestamo_mora1`
    FOREIGN KEY (`mora_id`)
    REFERENCES `mora` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_prestamo_cotizacion1_idx` ON `prestamo` (`cotizacion_id` ASC) VISIBLE;

CREATE INDEX `fk_prestamo_casillero1_idx` ON `prestamo` (`casillero_id` ASC) VISIBLE;

CREATE INDEX `fk_prestamo_interes1_idx` ON `prestamo` (`interes_id` ASC) VISIBLE;

CREATE INDEX `fk_prestamo_mora1_idx` ON `prestamo` (`mora_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tipocomprobante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipocomprobante` ;

CREATE TABLE IF NOT EXISTS `tipocomprobante` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipocomprobante` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tipopago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipopago` ;

CREATE TABLE IF NOT EXISTS `tipopago` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipopago` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pago` ;

CREATE TABLE IF NOT EXISTS `pago` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `monto` VARCHAR(45) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `serie` VARCHAR(45) NULL DEFAULT NULL,
  `prestamo_id` INT(11) NOT NULL,
  `tipopago_id` INT(11) NOT NULL,
  `tipocomprobante_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pago_prestamo1`
    FOREIGN KEY (`prestamo_id`)
    REFERENCES `prestamo` (`id`),
  CONSTRAINT `fk_pago_tipocomprobante1`
    FOREIGN KEY (`tipocomprobante_id`)
    REFERENCES `tipocomprobante` (`id`),
  CONSTRAINT `fk_pago_tipopago1`
    FOREIGN KEY (`tipopago_id`)
    REFERENCES `tipopago` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_pago_prestamo1_idx` ON `pago` (`prestamo_id` ASC) VISIBLE;

CREATE INDEX `fk_pago_tipopago1_idx` ON `pago` (`tipopago_id` ASC) VISIBLE;

CREATE INDEX `fk_pago_tipocomprobante1_idx` ON `pago` (`tipocomprobante_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `precio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `precio` ;

CREATE TABLE IF NOT EXISTS `precio` (
  `idprecio` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` VARCHAR(45) NOT NULL,
  `detalle` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idprecio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `requisitos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `requisitos` ;

CREATE TABLE IF NOT EXISTS `requisitos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `detalle` VARCHAR(450) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tipoprest_requisito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipoprest_requisito` ;

CREATE TABLE IF NOT EXISTS `tipoprest_requisito` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `requisitos_id` INT(11) NOT NULL,
  `tipoprestamo_id` INT(11) NOT NULL,
  `detalle` VARCHAR(450) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tipoprest_requisito_requisitos1`
    FOREIGN KEY (`requisitos_id`)
    REFERENCES `requisitos` (`id`),
  CONSTRAINT `fk_tipoprest_requisito_tipoprestamo1`
    FOREIGN KEY (`tipoprestamo_id`)
    REFERENCES `tipoprestamo` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tipoprest_requisito_requisitos1_idx` ON `tipoprest_requisito` (`requisitos_id` ASC) VISIBLE;

CREATE INDEX `fk_tipoprest_requisito_tipoprestamo1_idx` ON `tipoprest_requisito` (`tipoprestamo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tipotelefono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipotelefono` ;

CREATE TABLE IF NOT EXISTS `tipotelefono` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(450) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `telefono_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tipotelefono_telefono1`
    FOREIGN KEY (`telefono_id`)
    REFERENCES `telefono` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tipotelefono_telefono1_idx` ON `tipotelefono` (`telefono_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `caja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `caja` ;

CREATE TABLE IF NOT EXISTS `caja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  `fecinicio` DATE NULL,
  `fecfin` DATE NULL,
  `montoinicio` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_caja_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_caja_users1_idx` ON `caja` (`users_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `movcaja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movcaja` ;

CREATE TABLE IF NOT EXISTS `movcaja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `detalle` VARCHAR(45) NULL,
  `monto` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `caja_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_movcaja_caja1`
    FOREIGN KEY (`caja_id`)
    REFERENCES `caja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_movcaja_caja1_idx` ON `movcaja` (`caja_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
